from core_tool import *


def Help():
    pass


def Run(ct, *args):
    pass
    for i in range(20,30):
        print(i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.Er', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM4Sig003_gnnsd1_ggmm1', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM4Sig003_gnnsd1_ggmm1_LCB2', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM4Sig005_gnnsd1_ggmm1', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM4Sig005_gnnsd1_ggmm1_LCB2', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM4Sig003_gnnsd1_ggmm2', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM4Sig003_gnnsd1_ggmm2_LCB2', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM4Sig003_gnnsd1_ggmm3', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM4Sig005_gnnsd1_ggmm2', i)    
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM5Sig003_gnnsd1_ggmm1', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM6Sig001_LCB1', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM6Sig003_LCB1', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM6Sig0002_LCB1', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.Er', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMMSig5LCB3', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig5LCB3', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig5LCB3_update', i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig5LCB3_checkpoint', 51+2*(i-1)+1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig5LCB3_checkpoint', 51+2*(i-1))
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig5LCB6_checkpoint', 51+2*(i-1)+1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig5LCB6_checkpoint', 51+2*(i-1))
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.TMMSig8_checkpoint',i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.TMMSig8_checkpoint',2*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.TMMSig8_checkpoint',2*i+1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.ErLCB4_checkpoint',2*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.ErLCB4_checkpoint',2*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.ErLCB4_checkpoint',i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig8LCB4_checkpoint',2*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig8LCB4_checkpoint',2*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig8LCB4_without5963_checkpoint',i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.TMMSig8LCB4_without5963_checkpoint',i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.TMMSig8LCB4_checkpoint',2*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.TMMSig8LCB4_checkpoint',2*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig5LCB4_checkpoint',2*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig5LCB4_checkpoint',2*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig8LCB4_sort',i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM9Sig8LCB4_chop_sort',i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM11Sig8LCB4_checkpoint',2*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM11Sig8LCB4_checkpoint',2*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM11Sig8LCB4_checkpoint',i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig8LCB4_checkpoint',4*i-3)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig8LCB4_checkpoint',4*i-2)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig8LCB4_checkpoint',4*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig8LCB4_checkpoint',4*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.offpolicy.sample',i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig10LCB4_checkpoint',2*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig10LCB4_checkpoint',2*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig12LCB4_checkpoint',2*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig12LCB4_checkpoint',2*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig12LCB4_checkpoint',4*i-3)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig12LCB4_checkpoint',4*i-2)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig12LCB4_checkpoint',4*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig12LCB4_checkpoint',4*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig6LCB4_checkpoint',2*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig6LCB4_checkpoint',2*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig4LCB4_checkpoint',2*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy2.GMM12Sig4LCB4_checkpoint',2*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.learn3_nobounce',3*i-2)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.learn3_nobounce',3*i-1)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.learn3_nobounce',3*i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy3.GMM12Sig8LCB4_checkpoint',i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy3.Er',i)
        # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy4.GMM12Sig8LCB4_checkpoint',i)
        ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy4.GMM12Sig8LCB4_def_checkpoint',i)
    # for i in range(11,40):
    #     print(i)
    #     # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.Er', i)
    #     # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.Er_LCB2', i)
    #     # ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM4Sig003_gnnsd1_ggmm1', i)
    #     ct.Run('mysim.curriculum.analyze.log.curriculum5.c1.trues_sampling.tip_ketchup_smsz_dtheta2.opttest.onpolicy.GMM4Sig003_gnnsd1_ggmm1_LCB2', i)